control_node:
  ros__parameters:
    # Controller params
    lambda: [1.0, 1.0, 1.0]
    k: [2.0, 2.0, 2.0]
    gammaInv: [10.0, 10.0, 10.0]

    # Deadzone params
    del: 0.5
    e0: 0.025

    # Projection params
    epsilon: 0.5
    thetaMax: 100.0
    