control_node:
  ros__parameters:
    # Node params
    controlRate: 0.01
    controller: "passivityBasedAdaptiveControl"
    reset: "passivityBasedAdaptiveControlReset"

    # Required controller params
    lambda: [1.0, 1.0, 1.0]
    k: [2.0, 2.0, 2.0]
    gammaInv: [10.0, 10.0, 10.0]
    del: 0.5 # deadzone params
    e0: 0.025 # deadzone params
    epsilon: 0.5 # projection params
    thetaMax: 100.0 # Projection params

    # Initial parameter estimates
    theta: [0.0, 0.0, 0.0]